name: Pre Commit

on:
  push:

jobs:
  call-pre-commit:
    uses: ElKiwos/workflow-test-source/.github/workflows/pre-commit.yaml@main

---
name: Tag commit

on:
  workflow_dispatch:

jobs:
  call-tag-commit:
    uses: ElKiwos/workflow-test-source/.github/workflows/tag.yaml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
